#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from respingtk import respin_gtk

if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.realpath(respin_gtk.__file__)))
    #os.system('chmod a+x %s' % respin_gtk.__file__)
