.TH RESPIN 1 "September 30, 2014" 
.SH NAME
respin-gtk \- official gui for respin
.SH SYNOPSIS
sudo respin-gtk 
.br
.br
 
.SH DESCRIPTION
Respin is a script used to make a bootable live cd or dvd from an
installed Ubuntu system or derivative. This is the gui.
.PP
This manual page documents
.BR respin .
.B respin
Makes a live cd or dvd iso file from and installed system

Makes system backup minus the user folders.
.SH AUTHOR
adrenaline, Sergio Mejia, Marcia Wilbur 2014
Tony Brijeski - Copyright (c) 2007,2008,2009,2010,2011,2012
.SH BUG REPORT
Report bugs to bugs@linuxrespin.org
.SH URL
http://www.linuxrespin.org
